// Curated, family-friendly word bank for Draw & Guess (260+ words)
export const WORD_BANK = [
  // --- Animals (40) ---
  { word: "elephant", category: "Animals", hint: "Large mammal with a trunk" },
  { word: "giraffe", category: "Animals", hint: "Tallest mammal with a long neck" },
  { word: "penguin", category: "Animals", hint: "Flightless bird in tuxedos" },
  { word: "kangaroo", category: "Animals", hint: "Hops and carries babies in a pouch" },
  { word: "octopus", category: "Animals", hint: "Sea creature with eight arms" },
  { word: "dolphin", category: "Animals", hint: "Smart, playful marine mammal" },
  { word: "panda", category: "Animals", hint: "Black and white bamboo eater" },
  { word: "tiger", category: "Animals", hint: "Striped big cat" },
  { word: "lion", category: "Animals", hint: "King of the jungle with a mane" },
  { word: "zebra", category: "Animals", hint: "Black and white striped horse cousin" },
  { word: "monkey", category: "Animals", hint: "Loves bananas and swings in trees" },
  { word: "turtle", category: "Animals", hint: "Slow reptile with a hard shell" },
  { word: "rabbit", category: "Animals", hint: "Long ears and loves carrots" },
  { word: "owl", category: "Animals", hint: "Nocturnal bird that turns its head" },
  { word: "eagle", category: "Animals", hint: "Majestic bird of prey" },
  { word: "crocodile", category: "Animals", hint: "Large aquatic reptile with big teeth" },
  { word: "frog", category: "Animals", hint: "Amphibian that catches flies with its tongue" },
  { word: "shark", category: "Animals", hint: "Ocean predator with a dorsal fin" },
  { word: "butterfly", category: "Animals", hint: "Insect with colorful wings" },
  { word: "camel", category: "Animals", hint: "Desert traveler with humps" },
  { word: "flamingo", category: "Animals", hint: "Pink bird standing on one leg" },
  { word: "bear", category: "Animals", hint: "Large furry mammal that hibernates" },
  { word: "wolf", category: "Animals", hint: "Wild canine that howls at the moon" },
  { word: "fox", category: "Animals", hint: "Clever reddish creature with a bushy tail" },
  { word: "koala", category: "Animals", hint: "Australian eucalyptus sleeper" },
  { word: "whale", category: "Animals", hint: "Giant mammal of the deep ocean" },
  { word: "snake", category: "Animals", hint: "Legless reptile that hisses" },
  { word: "crab", category: "Animals", hint: "Crustacean that walks sideways" },
  { word: "duck", category: "Animals", hint: "Water bird that quacks" },
  { word: "sheep", category: "Animals", hint: "Woolly farm animal" },
  { word: "horse", category: "Animals", hint: "Gallops and wears horseshoes" },
  { word: "hedgehog", category: "Animals", hint: "Small spiky nocturnal mammal" },
  { word: "squirrel", category: "Animals", hint: "Bushy-tailed acorn collector" },
  { word: "parrot", category: "Animals", hint: "Colorful bird that mimics voices" },
  { word: "hippo", category: "Animals", hint: "Heavy river-dwelling mammal" },
  { word: "rhino", category: "Animals", hint: "Armored animal with horns on its snout" },
  { word: "peacock", category: "Animals", hint: "Bird that fans out eye-pattern feathers" },
  { word: "cheetah", category: "Animals", hint: "Fastest land animal on earth" },
  { word: "bat", category: "Animals", hint: "Flying nocturnal mammal" },
  { word: "bee", category: "Animals", hint: "Buzzes and makes sweet honey" },

  // --- Food & Drinks (36) ---
  { word: "pizza", category: "Food", hint: "Cheesy slice with toppings" },
  { word: "burger", category: "Food", hint: "Patty inside a bun" },
  { word: "ice cream", category: "Food", hint: "Cold sweet dessert on a cone" },
  { word: "banana", category: "Food", hint: "Yellow fruit you peel" },
  { word: "apple", category: "Food", hint: "Crisp red or green fruit" },
  { word: "taco", category: "Food", hint: "Folded tortilla filled with goodness" },
  { word: "sushi", category: "Food", hint: "Japanese rice roll wrapped in seaweed" },
  { word: "pancake", category: "Food", hint: "Flat cake topped with syrup" },
  { word: "donut", category: "Food", hint: "Sweet ring with a hole in the middle" },
  { word: "cookie", category: "Food", hint: "Baked sweet treat with chocolate chips" },
  { word: "sandwich", category: "Food", hint: "Fillings placed between two bread slices" },
  { word: "popcorn", category: "Food", hint: "Movie snack made from heated kernels" },
  { word: "cake", category: "Food", hint: "Sweet celebration dessert with candles" },
  { word: "watermelon", category: "Food", hint: "Juicy green melon with red inside" },
  { word: "cheese", category: "Food", hint: "Yellow dairy food loved by mice" },
  { word: "strawberry", category: "Food", hint: "Red berry with seeds on the outside" },
  { word: "hot dog", category: "Food", hint: "Sausage in a long sliced bun" },
  { word: "pasta", category: "Food", hint: "Italian noodles with sauce" },
  { word: "chocolate", category: "Food", hint: "Sweet brown treat from cocoa" },
  { word: "fries", category: "Food", hint: "Crispy fried potato sticks" },
  { word: "egg", category: "Food", hint: "Laid by hens, has a yolk" },
  { word: "carrot", category: "Food", hint: "Orange root vegetable" },
  { word: "bread", category: "Food", hint: "Baked staple food sliced for toast" },
  { word: "grapes", category: "Food", hint: "Bunch of purple or green sweet berries" },
  { word: "lemon", category: "Food", hint: "Sour yellow citrus fruit" },
  { word: "cupcake", category: "Food", hint: "Miniature cake baked in a paper cup" },
  { word: "pineapple", category: "Food", hint: "Tropical spiky fruit with crown" },
  { word: "waffle", category: "Food", hint: "Grid-patterned breakfast cake" },
  { word: "coffee", category: "Food", hint: "Morning hot caffeinated brew" },
  { word: "avocado", category: "Food", hint: "Green creamy fruit with a big seed" },
  { word: "mushroom", category: "Food", hint: "Fungus with an umbrella cap" },
  { word: "cherry", category: "Food", hint: "Small round red fruit with a stem" },
  { word: "lollipop", category: "Food", hint: "Hard candy on a stick" },
  { word: "biscuit", category: "Food", hint: "Crisp baked snack dipped in tea" },
  { word: "soup", category: "Food", hint: "Warm liquid dish in a bowl" },
  { word: "mango", category: "Food", hint: "Sweet tropical king of fruits" },

  // --- Objects (38) ---
  { word: "guitar", category: "Objects", hint: "Six-string musical instrument" },
  { word: "umbrella", category: "Objects", hint: "Keeps you dry when it rains" },
  { word: "clock", category: "Objects", hint: "Tells the time with hands" },
  { word: "camera", category: "Objects", hint: "Captures photographs and memories" },
  { word: "scissors", category: "Objects", hint: "Two blades used for cutting" },
  { word: "telephone", category: "Objects", hint: "Used to make phone calls" },
  { word: "glasses", category: "Objects", hint: "Worn on the face to see clearly" },
  { word: "key", category: "Objects", hint: "Unlocks doors and padlocks" },
  { word: "book", category: "Objects", hint: "Pages bound together for reading" },
  { word: "backpack", category: "Objects", hint: "Bag carried on your shoulders" },
  { word: "candle", category: "Objects", hint: "Wax with a burning wick" },
  { word: "mirror", category: "Objects", hint: "Shows your reflection" },
  { word: "watch", category: "Objects", hint: "Timepiece worn on the wrist" },
  { word: "lamp", category: "Objects", hint: "Provides light on a desk or table" },
  { word: "chair", category: "Objects", hint: "Furniture with four legs for sitting" },
  { word: "pencil", category: "Objects", hint: "Wooden writing tool with graphite" },
  { word: "balloon", category: "Objects", hint: "Inflatable rubber party toy" },
  { word: "crown", category: "Objects", hint: "Royal headpiece worn by kings" },
  { word: "compass", category: "Objects", hint: "Magnetic needle pointing North" },
  { word: "flashlight", category: "Objects", hint: "Handheld battery light torch" },
  { word: "telescope", category: "Objects", hint: "Used to gaze at stars in space" },
  { word: "shoe", category: "Objects", hint: "Footwear tied with laces" },
  { word: "bottle", category: "Objects", hint: "Container for holding liquids" },
  { word: "toothbrush", category: "Objects", hint: "Bristles for cleaning teeth" },
  { word: "suitcase", category: "Objects", hint: "Luggage case for travel" },
  { word: "pillow", category: "Objects", hint: "Soft cushion to rest your head" },
  { word: "whistle", category: "Objects", hint: "Blown to make a sharp loud sound" },
  { word: "ring", category: "Objects", hint: "Jewelry worn on a finger" },
  { word: "lock", category: "Objects", hint: "Fastener opened with a key" },
  { word: "bell", category: "Objects", hint: "Chimes when rung" },
  { word: "helmet", category: "Objects", hint: "Protective headgear for riders" },
  { word: "ladder", category: "Objects", hint: "Steps used for climbing up high" },
  { word: "bucket", category: "Objects", hint: "Pail for carrying water" },
  { word: "anchor", category: "Objects", hint: "Heavy iron dropped to moor ships" },
  { word: "magnet", category: "Objects", hint: "Attracts iron and metals" },
  { word: "envelope", category: "Objects", hint: "Paper cover for sending letters" },
  { word: "broom", category: "Objects", hint: "Used for sweeping floors" },
  { word: "microscope", category: "Objects", hint: "Magnifies tiny cells" },

  // --- Vehicles (24) ---
  { word: "bus", category: "Vehicles", hint: "Public transit bus carrying passengers" },
  { word: "airplane", category: "Vehicles", hint: "Wings and jets flying through clouds" },
  { word: "bicycle", category: "Vehicles", hint: "Two wheels propelled by pedals" },
  { word: "submarine", category: "Vehicles", hint: "Underwater naval vessel" },
  { word: "train", category: "Vehicles", hint: "Runs on railway tracks with an engine" },
  { word: "helicopter", category: "Vehicles", hint: "Rotors spinning on top to hover" },
  { word: "motorcycle", category: "Vehicles", hint: "Two-wheeled motorized ride" },
  { word: "boat", category: "Vehicles", hint: "Floats on water with oars or sail" },
  { word: "tractor", category: "Vehicles", hint: "Big wheeled farm vehicle" },
  { word: "spaceship", category: "Vehicles", hint: "Travels beyond Earth into the cosmos" },
  { word: "ambulance", category: "Vehicles", hint: "Emergency vehicle with a siren" },
  { word: "truck", category: "Vehicles", hint: "Heavy vehicle for moving cargo" },
  { word: "scooter", category: "Vehicles", hint: "Small two-wheeler with a footboard" },
  { word: "hot air balloon", category: "Vehicles", hint: "Giant basket flying by hot air" },
  { word: "skateboard", category: "Vehicles", hint: "Deck with four small wheels" },
  { word: "canoe", category: "Vehicles", hint: "Narrow open boat rowed with a paddle" },
  { word: "taxi", category: "Vehicles", hint: "Car hailed for a metered ride" },
  { word: "fire truck", category: "Vehicles", hint: "Red truck with hoses and ladders" },
  { word: "rocket", category: "Vehicles", hint: "Launches into space with fire" },
  { word: "sailboat", category: "Vehicles", hint: "Harnesses wind in large white sails" },
  { word: "van", category: "Vehicles", hint: "Boxy motor vehicle for groups" },
  { word: "hovercraft", category: "Vehicles", hint: "Glides over land and water on air cushion" },
  { word: "cable car", category: "Vehicles", hint: "Suspended cabin climbing mountains" },
  { word: "jeep", category: "Vehicles", hint: "Rugged 4x4 off-road vehicle" },

  // --- Places & Nature (34) ---
  { word: "mountain", category: "Nature", hint: "Giant elevated peak of rock" },
  { word: "volcano", category: "Nature", hint: "Mountain erupting with hot lava" },
  { word: "beach", category: "Nature", hint: "Sandy shore meeting the ocean waves" },
  { word: "island", category: "Nature", hint: "Land entirely surrounded by water" },
  { word: "waterfall", category: "Nature", hint: "River cascading down a cliff" },
  { word: "forest", category: "Nature", hint: "Large area filled with tall trees" },
  { word: "desert", category: "Nature", hint: "Dry sandy land with cactus" },
  { word: "castle", category: "Places", hint: "Fortified palace with stone towers" },
  { word: "pyramid", category: "Places", hint: "Ancient triangular monument in Egypt" },
  { word: "lighthouse", category: "Places", hint: "Tower beaming light to ships at sea" },
  { word: "igloo", category: "Places", hint: "Dome shelter built from blocks of ice" },
  { word: "bridge", category: "Places", hint: "Structure connecting across water" },
  { word: "rainbow", category: "Nature", hint: "Seven colors arching across the sky" },
  { word: "sun", category: "Nature", hint: "Bright star giving Earth daylight" },
  { word: "moon", category: "Nature", hint: "Glowing celestial body in night sky" },
  { word: "star", category: "Nature", hint: "Twinkling light in the night sky" },
  { word: "cloud", category: "Nature", hint: "Fluffy white vapor floating in blue sky" },
  { word: "lightning", category: "Nature", hint: "Flash of electricity during thunder" },
  { word: "campfire", category: "Nature", hint: "Outdoor logs burning under the stars" },
  { word: "cave", category: "Nature", hint: "Dark hollow opening inside a mountain" },
  { word: "river", category: "Nature", hint: "Flowing freshwater stream to the sea" },
  { word: "planet", category: "Nature", hint: "Orbits the sun, like Earth or Mars" },
  { word: "garden", category: "Nature", hint: "Plot where colorful flowers bloom" },
  { word: "windmill", category: "Places", hint: "Rotates blades to generate wind energy" },
  { word: "tent", category: "Places", hint: "Portable canvas shelter for camping" },
  { word: "barn", category: "Places", hint: "Farm building storing hay and animals" },
  { word: "fountain", category: "Places", hint: "Jets of decorative water shooting upward" },
  { word: "ocean", category: "Nature", hint: "Vast expanse of blue saltwater" },
  { word: "treehouse", category: "Places", hint: "Wooden playhouse built in branches" },
  { word: "stadium", category: "Places", hint: "Arena packed with sports fans" },
  { word: "swimming pool", category: "Places", hint: "Artificial water basin for swimming" },
  { word: "lake", category: "Nature", hint: "Calm body of water surrounded by land" },
  { word: "canyon", category: "Nature", hint: "Deep rocky gorge carved by rivers" },
  { word: "glacier", category: "Nature", hint: "Slowly moving massive river of ice" },

  // --- Jobs & Characters (28) ---
  { word: "doctor", category: "Jobs", hint: "Heals patients and wears a stethoscope" },
  { word: "firefighter", category: "Jobs", hint: "Extinguishes flames and saves lives" },
  { word: "astronaut", category: "Jobs", hint: "Travels in a spacesuit beyond Earth" },
  { word: "chef", category: "Jobs", hint: "Cooks gourmet dishes wearing a tall hat" },
  { word: "pirate", category: "Characters", hint: "Eyepatch, parrot, searching for treasure" },
  { word: "detective", category: "Jobs", hint: "Investigates clues with a magnifying glass" },
  { word: "ninja", category: "Characters", hint: "Silent martial artist in black mask" },
  { word: "painter", category: "Jobs", hint: "Creates artwork on canvas with brushes" },
  { word: "farmer", category: "Jobs", hint: "Grows crops and raises farm animals" },
  { word: "pilot", category: "Jobs", hint: "Flies airplanes in the cockpit" },
  { word: "scientist", category: "Jobs", hint: "Experiments with beakers in a lab" },
  { word: "magician", category: "Characters", hint: "Pulls rabbits from top hats" },
  { word: "dancer", category: "Jobs", hint: "Expresses rhythm with graceful moves" },
  { word: "police", category: "Jobs", hint: "Upholds law and wears a badge" },
  { word: "dentist", category: "Jobs", hint: "Inspects and cleans your teeth" },
  { word: "king", category: "Characters", hint: "Monarch wearing a golden crown" },
  { word: "queen", category: "Characters", hint: "Female ruler in regal gowns" },
  { word: "superhero", category: "Characters", hint: "Wears a cape and has superpowers" },
  { word: "sailor", category: "Jobs", hint: "Navigates vessels across the sea" },
  { word: "soldier", category: "Jobs", hint: "Serves in uniform for the military" },
  { word: "teacher", category: "Jobs", hint: "Educates students in a classroom" },
  { word: "driver", category: "Jobs", hint: "Operates buses, cars, or cabs" },
  { word: "robot", category: "Characters", hint: "Mechanical android programmed with code" },
  { word: "ghost", category: "Characters", hint: "Spooky spectral figure saying Boo" },
  { word: "mermaid", category: "Characters", hint: "Mythical maiden with a fish tail" },
  { word: "wizard", category: "Characters", hint: "Casts magical spells with a wand" },
  { word: "vampire", category: "Characters", hint: "Fangs, cape, avoids daylight" },
  { word: "alien", category: "Characters", hint: "Extraterrestrial life from Mars" },

  // --- Sports & Activities (24) ---
  { word: "football", category: "Sports", hint: "Played with a patterned round ball" },
  { word: "basketball", category: "Sports", hint: "Dribble and shoot through the hoop" },
  { word: "tennis", category: "Sports", hint: "Racket hitting a yellow ball over net" },
  { word: "swimming", category: "Sports", hint: "Gliding through water with strokes" },
  { word: "skiing", category: "Sports", hint: "Sliding down snowy slopes on planks" },
  { word: "surfing", category: "Sports", hint: "Riding ocean waves on a board" },
  { word: "bowling", category: "Sports", hint: "Rolling a heavy ball to strike ten pins" },
  { word: "fishing", category: "Sports", hint: "Casting a line with a hook into water" },
  { word: "dancing", category: "Sports", hint: "Moving body in rhythm to the beat" },
  { word: "boxing", category: "Sports", hint: "Padded gloves inside a boxing ring" },
  { word: "golf", category: "Sports", hint: "Swinging clubs to putt ball into hole" },
  { word: "archery", category: "Sports", hint: "Drawing a bow to shoot an arrow at bullseye" },
  { word: "running", category: "Sports", hint: "Sprinting with athletic sneakers" },
  { word: "yoga", category: "Sports", hint: "Stretching and balancing on a mat" },
  { word: "camping", category: "Sports", hint: "Sleeping in tents by the campfire" },
  { word: "karate", category: "Sports", hint: "Martial art with belts and kicks" },
  { word: "baseball", category: "Sports", hint: "Hitting a pitch with a wooden bat" },
  { word: "cricket", category: "Sports", hint: "Bowler, batsman, and three wickets" },
  { word: "badminton", category: "Sports", hint: "Hitting a feathered shuttlecock" },
  { word: "skating", category: "Sports", hint: "Gliding on ice or roller blades" },
  { word: "climbing", category: "Sports", hint: "Scaling rock faces with ropes" },
  { word: "diving", category: "Sports", hint: "Leaping off high board into the pool" },
  { word: "fencing", category: "Sports", hint: "Sword duel in white protective gear" },
  { word: "gardening", category: "Sports", hint: "Planting seeds and watering flowers" },

  // --- Everyday Concepts & Themes (38) ---
  { word: "birthday", category: "Celebration", hint: "Party with cake, gifts, and balloons" },
  { word: "music", category: "Entertainment", hint: "Melody, rhythm, and song notes" },
  { word: "treasure", category: "Adventure", hint: "Chest filled with golden coins" },
  { word: "fireworks", category: "Celebration", hint: "Spectacular colored explosions in night sky" },
  { word: "snowman", category: "Winter", hint: "Figure made of snow with a carrot nose" },
  { word: "sunflower", category: "Nature", hint: "Tall plant following the sun" },
  { word: "kite", category: "Toys", hint: "Diamond flying high on a string" },
  { word: "yoyo", category: "Toys", hint: "Spool spinning up and down a string" },
  { word: "puzzle", category: "Toys", hint: "Fitting jigsaw pieces together" },
  { word: "heart", category: "Symbols", hint: "Symbol of love and affection" },
  { word: "diamond", category: "Jewelry", hint: "Sparkling precious gemstone" },
  { word: "trophy", category: "Awards", hint: "Golden cup awarded to champions" },
  { word: "medal", category: "Awards", hint: "Gold, silver, or bronze ribbon award" },
  { word: "drum", category: "Music", hint: "Beaten with drumsticks for a beat" },
  { word: "piano", category: "Music", hint: "Keys of black and white harmonies" },
  { word: "microphone", category: "Music", hint: "Amplifies a singer's voice" },
  { word: "headphones", category: "Music", hint: "Worn over ears for private music" },
  { word: "radio", category: "Music", hint: "Tuned into stations for broadcasts" },
  { word: "stairs", category: "Architecture", hint: "Steps leading up to the next floor" },
  { word: "door", category: "Architecture", hint: "Has a knob and swings open" },
  { word: "window", category: "Architecture", hint: "Glass opening to look outside" },
  { word: "chimney", category: "Architecture", hint: "Smoke rises from fireplace out this" },
  { word: "fence", category: "Architecture", hint: "Pickets bordering a yard" },
  { word: "mailbox", category: "Everyday", hint: "Where letters and parcels are delivered" },
  { word: "map", category: "Adventure", hint: "Chart showing roads and continents" },
  { word: "shield", category: "Combat", hint: "Held to block swords and arrows" },
  { word: "sword", category: "Combat", hint: "Bladed weapon with a hilt" },
  { word: "treasure chest", category: "Adventure", hint: "Wooden box bound with brass" },
  { word: "telescope", category: "Science", hint: "Aims at planets in the night sky" },
  { word: "magnet", category: "Science", hint: "Horseshoe with red and blue poles" },
  { word: "battery", category: "Tech", hint: "Powers devices with positive and negative" },
  { word: "computer", category: "Tech", hint: "Screen, keyboard, and processor" },
  { word: "television", category: "Tech", hint: "Screen showing shows and movies" },
  { word: "gamepad", category: "Tech", hint: "Controller with buttons and joysticks" },
  { word: "traffic light", category: "Travel", hint: "Red, yellow, and green signals" },
  { word: "stop sign", category: "Travel", hint: "Red octagon alerting drivers to halt" },
  { word: "sleeping", category: "Everyday", hint: "Eyes closed dreaming in bed" },
  { word: "reading", category: "Everyday", hint: "Looking at words in a book" }
];
